name = "puddle-pools-southern-nevada2"
compatibility_date = "2026-08-31"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "puddle-pools-ops"
database_id = "6bcda2e3-548e-4ed3-943a-f04952044c99"

[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "puddle-pools-uploads"
