const USERS={
 'tech@demo.local':{password:'demo123',name:'Alex Tech',role:'Technician',level:'tech',truck:'Truck 02 — Ford Transit'},
 'manager@demo.local':{password:'demo123',name:'Maria Manager',role:'Manager',level:'manager',truck:'Truck 01 — Ford Transit'},
 'admin@demo.local':{password:'demo123',name:'System Admin',role:'Administrator',level:'admin',truck:'Fleet Access'}
};
const rank={tech:1,manager:2,admin:3};let current=null;
const login=document.querySelector('#loginScreen'),app=document.querySelector('#app');
function boot(user){current=user;login.classList.add('hidden');app.classList.remove('hidden');document.querySelector('#userName').textContent=user.name;document.querySelector('#userRole').textContent=user.role;document.querySelector('#assignedTruck').textContent=user.truck;document.querySelector('#truckName').textContent=user.truck.split(' — ')[0];document.querySelectorAll('[data-perm]').forEach(el=>{if(rank[user.level]<(el.dataset.perm==='admin'?3:2))el.classList.add('hidden');else el.classList.remove('hidden')});show('dashboard');}
document.querySelector('#loginForm').addEventListener('submit',e=>{e.preventDefault();const email=document.querySelector('#email').value.toLowerCase(),pw=document.querySelector('#password').value,u=USERS[email];if(u&&u.password===pw){sessionStorage.setItem('pp_demo_user',email);boot(u)}else document.querySelector('#loginMsg').textContent='Invalid demo credentials.'});
document.querySelector('#logout').addEventListener('click',()=>{sessionStorage.removeItem('pp_demo_user');location.reload()});
function show(id){document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));document.querySelector('#'+id)?.classList.remove('hidden');document.querySelector('#viewTitle').textContent=id[0].toUpperCase()+id.slice(1);document.querySelectorAll('aside nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));document.querySelector('aside').classList.remove('open')}
document.querySelectorAll('[data-view]').forEach(el=>el.addEventListener('click',()=>show(el.dataset.view)));document.querySelector('#mobileNav').addEventListener('click',()=>document.querySelector('aside').classList.toggle('open'));
let inv=JSON.parse(localStorage.getItem('pp_inv')||'null')||[{item:'Liquid Chlorine',category:'Chemical',par:4,onHand:3},{item:'Muriatic Acid',category:'Chemical',par:3,onHand:4},{item:'Stabilizer / CYA',category:'Chemical',par:1,onHand:1},{item:'Test Reagents',category:'Testing',par:2,onHand:1},{item:'Skimmer Baskets',category:'Parts',par:2,onHand:3}];
function renderInv(){const b=document.querySelector('#invBody');b.innerHTML='';inv.forEach((x,i)=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${x.item}<\/td><td>${x.category}<\/td><td>${x.par}<\/td><td contenteditable="true" data-i="${i}">${x.onHand}<\/td><td class="${x.onHand<x.par?'status-low':'status-ok'}">${x.onHand<x.par?'REORDER':'OK'}<\/td>`;b.appendChild(tr)});b.querySelectorAll('[contenteditable]').forEach(td=>td.addEventListener('blur',()=>{inv[+td.dataset.i].onHand=Number(td.textContent)||0;localStorage.setItem('pp_inv',JSON.stringify(inv));renderInv()}))}renderInv();
document.querySelector('#addItem').addEventListener('click',()=>{const item=prompt('Item name');if(!item)return;inv.push({item,category:'Other',par:1,onHand:0});localStorage.setItem('pp_inv',JSON.stringify(inv));renderInv()});
document.querySelector('#inspectionForm').addEventListener('submit',async e=>{e.preventDefault();const msg=document.querySelector('#inspectionMsg');msg.textContent='Submitting…';const fd=new FormData(e.target);try{const r=await fetch('/api/inspection',{method:'POST',body:fd});if(!r.ok)throw new Error();msg.textContent='Inspection submitted.';e.target.reset()}catch(err){const data=Object.fromEntries(fd.entries());localStorage.setItem('pp_last_inspection',JSON.stringify({...data,submitted_at:new Date().toISOString()}));msg.textContent='Demo mode: inspection saved locally. Cloudflare API files are included for production.'}});
document.querySelector('#uploadDoc').addEventListener('click',()=>document.querySelector('#docInput').click());document.querySelector('#docInput').addEventListener('change',e=>alert(`${e.target.files.length} file(s) selected. Production uploads use the included R2 endpoint.`));
const remembered=sessionStorage.getItem('pp_demo_user');if(remembered&&USERS[remembered])boot(USERS[remembered]);